#docker-compose.yml (Development)
version: "3.8"
services:
  web:
    image: pages-server
    environment:
      - APP_ENV=development
    container_name: pages-server
    restart: always
    build:
      context: .
      # Uncomment to deploy from Git
      #args:
      #  GIT_DEPLOY_URL:
      #  GIT_DEPLOY_BRANCH: master
    # Uncomment to override environment defaults
    #env_file:
    #  - .env
    volumes:
      - ./volume:/mnt/www
      - ./:/var/www
    ports:
      - "8080:8080"  # HTTP Apache
      - "8443:8443"  # HTTPS Apache
      - "8081:8081"  # HTTP Service - FastCGI
      - "8082:8082"  # HTTP Service - Webhooks