#docker-compose.yml (Development)
version: "3.8"
services:
  web:
    image: joomlatools-server
    environment:
      - APP_ENV=development
      - APP_DEBUG=1
      - AUTH0_DOMAIN=under-the-radar-report.au.auth0.com
      - AUTH0_CLIENT_ID=lnITJQiCdHw656mwC12viJHWJrPiVkld
      - AUTH0_CLIENT_SECRET=bGYpDk7Hz-aRPh6o247jV_2C-f2NXf1MmeSvum6Ytj29mcfitn0urp130zOawxmf
      - AUTH0_M2M_CLIENT_ID=ODHpTQt1nKkRwl4v0AgAyZSNmuO4Tue5
      - AUTH0_M2M_CLIENT_SECRET=Zcf0UYR38kxcbo5KDARG_NKkObtY5b3aaCF_DctrsjaKio6wjL0cVr_u6TZAP7Sx
      - AUTH0_REDIRECT_URI=http://localhost
      - CB_TEST_CLIENT=undertheradarreport-test
      - CB_TEST_KEY=test_3Yp30IDzYdfQgLSU6cXyv8eZL0y9MEw9
      - APP_PRELOAD=off
      - APP_DEBUG=on
      - APP_CACHE=off
      - APP_HTTP=8080
      - APP_HTTPS=8443
    container_name: joomlatools-server
    restart: always
    build:
      context: .
      # Uncomment to deploy from Git
      #args:
      #  GIT_DEPLOY_URL:
      #  GIT_DEPLOY_BRANCH: master
    # Uncomment to override environment defaults
    #env_file:
    #  - .env
    volumes:
      - ./volume:/mnt/www
      - ./:/var/www
    ports:
      - "80:8080"  # HTTP Apache
      - "443:8443"  # HTTPS Apache
      - "8081:8081"  # HTTP Service - FastCGI
      - "8082:8082"  # HTTP Service - Webhooks
      - "3306:3306"    # MySQL
      - "33060:33060"  # MySQL - X Plugin