#docker-compose.yml (Development)
version: "3.8"
services:
  web:
    image: joomlatools-server
    environment:
      - APP_ENV=development
      - APP_DEBUG=1
      - APP_PRELOAD=off
      - APP_DEBUG=on
      - APP_CACHE=off
      - APP_HTTP=8080
      - APP_HTTPS=8443
    container_name: joomlatools-server
    restart: always
    build:
      context: .
      # Uncomment to deploy from Git
      #args:
      #  GIT_DEPLOY_URL:
      #  GIT_DEPLOY_BRANCH: master
    # Uncomment to override environment defaults
    #env_file:
    #  - .env
    volumes:
      - ./volume:/mnt/www
      - ./:/var/www
    ports:
      - "80:8080"  # HTTP Apache
      - "443:8443"  # HTTPS Apache
      - "8081:8081"  # HTTP Service - FastCGI
      - "8082:8082"  # HTTP Service - Webhooks
      - "3306:3306"    # MySQL
      - "33060:33060"  # MySQL - X Plugin