# fly.toml file generated for divine-surf-1893 on 2021-10-18T17:41:02+11:00

app = "divine-surf-1893"

kill_signal = "SIGTERM"
kill_timeout = 10

[env]
  APP_CACHE = 1
  APP_DEBUG = 1
  APP_ENV = "development"
  APP_HTTP=80
  APP_HTTPS=443

# Uncomment to deploy from Git
#[build.args]
#  GIT_DEPLOY_URL =
#  GIT_DEPLOY_BRANCH = "master"

[experimental]
  auto_rollback = true
  private_network = true

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "10s"
    interval = "15"
    method = "get"
    path = "/__ping"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = true

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
